-- Seed: the full service catalogue that used to be hardcoded on the
-- booking site, now editable from the admin Services & Packages page.
-- Run in Supabase Dashboard > SQL Editor (after 010_services.sql).
insert into public.services
  (category_id, name, name_ar, description, duration_minutes, price, is_package, active, sort_order)
values
  ((select id from public.service_categories where name = 'Hair'), 'Haircut and trimming', 'قص وتهذيب الشعر', null, 45, 70, false, true, 10),
  ((select id from public.service_categories where name = 'Hair'), 'Blow-dry and hairstyling', 'تجفيف وتصفيف الشعر', null, 45, 80, false, true, 20),
  ((select id from public.service_categories where name = 'Hair'), 'Hair wash and conditioning', 'غسل وترطيب الشعر', null, 30, 45, false, true, 30),
  ((select id from public.service_categories where name = 'Hair'), 'Hair straightening and curling', 'فرد وتجعيد الشعر', null, 60, 90, false, true, 40),
  ((select id from public.service_categories where name = 'Hair'), 'Hair coloring and root touch-up', 'صبغ الشعر وتغطية الجذور', null, 90, 160, false, true, 50),
  ((select id from public.service_categories where name = 'Hair'), 'Highlights, lowlights, balayage and ombré', 'هايلايت ولولايت وبالياج وأومبريه', null, 150, 320, false, true, 60),
  ((select id from public.service_categories where name = 'Hair'), 'Hair bleaching and toning', 'تفتيح وتوحيد لون الشعر', null, 120, 260, false, true, 70),
  ((select id from public.service_categories where name = 'Hair'), 'Keratin and protein treatments', 'علاجات الكيراتين والبروتين', null, 120, 350, false, true, 80),
  ((select id from public.service_categories where name = 'Hair'), 'Hair botox', 'بوتوكس الشعر', null, 120, 300, false, true, 90),
  ((select id from public.service_categories where name = 'Hair'), 'Hair rebonding and relaxing', 'إعادة هيكلة وفرد الشعر', null, 180, 400, false, true, 100),
  ((select id from public.service_categories where name = 'Hair'), 'Hair spa and deep conditioning', 'سبا الشعر والترطيب العميق', null, 60, 120, false, true, 110),
  ((select id from public.service_categories where name = 'Hair'), 'Scalp treatment and dandruff care', 'علاج فروة الرأس والقشرة', null, 45, 110, false, true, 120),
  ((select id from public.service_categories where name = 'Nails'), 'Classic manicure and pedicure', 'مانيكير وباديكير كلاسيكي', null, 60, 90, false, true, 10),
  ((select id from public.service_categories where name = 'Nails'), 'Spa manicure and pedicure', 'مانيكير وباديكير سبا', null, 75, 130, false, true, 20),
  ((select id from public.service_categories where name = 'Nails'), 'Gel manicure and pedicure', 'مانيكير وباديكير جل', null, 75, 150, false, true, 30),
  ((select id from public.service_categories where name = 'Nails'), 'French manicure', 'مانيكير فرنسي', null, 45, 70, false, true, 40),
  ((select id from public.service_categories where name = 'Nails'), 'Nail polish application', 'وضع طلاء الأظافر', null, 20, 35, false, true, 50),
  ((select id from public.service_categories where name = 'Nails'), 'Gel polish removal', 'إزالة طلاء الجل', null, 20, 30, false, true, 60),
  ((select id from public.service_categories where name = 'Nails'), 'Acrylic nail extensions', 'تركيب أظافر أكريليك', null, 90, 200, false, true, 70),
  ((select id from public.service_categories where name = 'Nails'), 'Gel nail extensions', 'تركيب أظافر جل', null, 90, 190, false, true, 80),
  ((select id from public.service_categories where name = 'Nails'), 'Builder gel and polygel', 'جل بناء وبولي جل', null, 90, 210, false, true, 90),
  ((select id from public.service_categories where name = 'Nails'), 'Nail refill and repair', 'تعبئة وإصلاح الأظافر', null, 60, 120, false, true, 100),
  ((select id from public.service_categories where name = 'Nails'), 'Nail art', 'رسم الأظافر', null, 30, 60, false, true, 110),
  ((select id from public.service_categories where name = 'Nails'), 'Paraffin treatment', 'علاج البارافين', null, 30, 70, false, true, 120),
  ((select id from public.service_categories where name = 'Nails'), 'Foot scrub and callus removal', 'تقشير القدم وإزالة الجلد الميت', null, 45, 90, false, true, 130),
  ((select id from public.service_categories where name = 'Nails'), 'Ingrown nail care', 'العناية بالأظافر الغائرة', null, 30, 80, false, true, 140),
  ((select id from public.service_categories where name = 'Facial'), 'Basic facial', 'تنظيف بشرة أساسي', null, 45, 120, false, true, 10),
  ((select id from public.service_categories where name = 'Facial'), 'Deep-cleansing facial', 'تنظيف بشرة عميق', null, 60, 180, false, true, 20),
  ((select id from public.service_categories where name = 'Facial'), 'Hydrating facial', 'فيشل ترطيب', null, 60, 190, false, true, 30),
  ((select id from public.service_categories where name = 'Facial'), 'Brightening facial', 'فيشل تفتيح', null, 60, 200, false, true, 40),
  ((select id from public.service_categories where name = 'Facial'), 'Anti-aging facial', 'فيشل مكافحة الشيخوخة', null, 75, 250, false, true, 50),
  ((select id from public.service_categories where name = 'Facial'), 'Acne-control facial', 'فيشل علاج حب الشباب', null, 60, 210, false, true, 60),
  ((select id from public.service_categories where name = 'Facial'), 'Sensitive-skin facial', 'فيشل للبشرة الحساسة', null, 60, 190, false, true, 70),
  ((select id from public.service_categories where name = 'Facial'), 'Oxygen facial', 'فيشل الأكسجين', null, 60, 260, false, true, 80),
  ((select id from public.service_categories where name = 'Facial'), 'HydraFacial', 'هيدرافيشل', null, 60, 350, false, true, 90),
  ((select id from public.service_categories where name = 'Facial'), 'LED light therapy', 'العلاج بالضوء', null, 30, 150, false, true, 100),
  ((select id from public.service_categories where name = 'Facial'), 'Face cleanup', 'تنظيف الوجه السريع', null, 30, 90, false, true, 110),
  ((select id from public.service_categories where name = 'Facial'), 'Blackhead extraction', 'إزالة الرؤوس السوداء', null, 30, 100, false, true, 120),
  ((select id from public.service_categories where name = 'Facial'), 'Face and neck massage', 'مساج الوجه والرقبة', null, 30, 110, false, true, 130),
  ((select id from public.service_categories where name = 'Waxing'), 'Eyebrow waxing', 'واكس الحواجب', null, 15, 30, false, true, 10),
  ((select id from public.service_categories where name = 'Waxing'), 'Upper-lip and chin waxing', 'واكس الشفة العليا والذقن', null, 15, 35, false, true, 20),
  ((select id from public.service_categories where name = 'Waxing'), 'Full-face waxing', 'واكس الوجه الكامل', null, 30, 80, false, true, 30),
  ((select id from public.service_categories where name = 'Waxing'), 'Underarm waxing', 'واكس الإبط', null, 15, 40, false, true, 40),
  ((select id from public.service_categories where name = 'Waxing'), 'Half-arm and full-arm waxing', 'واكس نصف أو كامل الذراع', null, 30, 70, false, true, 50),
  ((select id from public.service_categories where name = 'Waxing'), 'Half-leg and full-leg waxing', 'واكس نصف أو كامل الساق', null, 45, 110, false, true, 60),
  ((select id from public.service_categories where name = 'Waxing'), 'Stomach and back waxing', 'واكس البطن والظهر', null, 30, 90, false, true, 70),
  ((select id from public.service_categories where name = 'Waxing'), 'Bikini-line waxing', 'واكس خط البكيني', null, 30, 80, false, true, 80),
  ((select id from public.service_categories where name = 'Waxing'), 'Brazilian waxing', 'واكس برازيلي', null, 45, 130, false, true, 90),
  ((select id from public.service_categories where name = 'Waxing'), 'Full-body waxing', 'واكس الجسم الكامل', null, 90, 320, false, true, 100),
  ((select id from public.service_categories where name = 'Waxing'), 'Threading', 'إزالة الشعر بالخيط', null, 15, 30, false, true, 110),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Eyebrow shaping', 'تحديد الحواجب', null, 20, 45, false, true, 10),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Eyebrow threading', 'خيط الحواجب', null, 15, 30, false, true, 20),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Eyebrow tinting', 'صبغ الحواجب', null, 20, 55, false, true, 30),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Henna brows', 'حواجب بالحناء', null, 30, 80, false, true, 40),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Brow lamination', 'تصفيف الحواجب', null, 45, 160, false, true, 50),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Lash lifting', 'رفع الرموش', null, 45, 170, false, true, 60),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Classic lash extensions', 'تركيب رموش كلاسيك', null, 90, 220, false, true, 70),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Hybrid lash extensions', 'تركيب رموش هايبرد', null, 105, 280, false, true, 80),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Volume and mega-volume lashes', 'رموش فوليوم وميغا فوليوم', null, 120, 350, false, true, 90),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Lash refill', 'تعبئة الرموش', null, 60, 150, false, true, 100),
  ((select id from public.service_categories where name = 'Brows & Lashes'), 'Lash-extension removal', 'إزالة تركيبات الرموش', null, 30, 70, false, true, 110),
  ((select id from public.service_categories where name = 'Massage'), 'Relaxing massage', 'مساج استرخائي', null, 60, 180, false, true, 10),
  ((select id from public.service_categories where name = 'Massage'), 'Swedish massage', 'مساج سويدي', null, 60, 200, false, true, 20),
  ((select id from public.service_categories where name = 'Massage'), 'Deep-tissue massage', 'مساج الأنسجة العميقة', null, 60, 230, false, true, 30),
  ((select id from public.service_categories where name = 'Massage'), 'Hot-stone massage', 'مساج بالأحجار الساخنة', null, 75, 280, false, true, 40),
  ((select id from public.service_categories where name = 'Massage'), 'Aromatherapy massage', 'مساج بالزيوت العطرية', null, 60, 220, false, true, 50),
  ((select id from public.service_categories where name = 'Massage'), 'Lymphatic-drainage massage', 'مساج التصريف اللمفاوي', null, 60, 250, false, true, 60),
  ((select id from public.service_categories where name = 'Massage'), 'Head, neck and shoulder massage', 'مساج الرأس والرقبة والكتفين', null, 30, 120, false, true, 70),
  ((select id from public.service_categories where name = 'Massage'), 'Foot massage and reflexology', 'مساج القدم والعلاج الانعكاسي', null, 45, 150, false, true, 80),
  ((select id from public.service_categories where name = 'Massage'), 'Prenatal massage', 'مساج الحوامل', null, 60, 240, false, true, 90)
on conflict do nothing;
